use_frameworks!

platform :ios, '8.0'

target 'ZHLogining_Example' do
  pod 'ZHLogining', :path => '../'

  target 'ZHLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
