use_frameworks!

platform :ios, '8.0'

target 'ZHLogining_Example' do
  pod 'ZHLogining', :path => '../'
  pod 'ZHTest', :path => '../../ZHTest'
  
  
  target 'ZHLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
